<cfquery name="updatetable" datasource="#dts#">
ALTER TABLE `taftc_i`.`project` ADD COLUMN `DETAIL5` VARCHAR(45) AFTER `WSQ`,
 ADD COLUMN `DETAIL6` VARCHAR(45) AFTER `DETAIL5`,
 ADD COLUMN `DETAIL7` VARCHAR(45) AFTER `DETAIL6`,
 ADD COLUMN `DETAIL8` VARCHAR(45) AFTER `DETAIL7`;

</cfquery>