<cfquery name='getgroup' datasource='#dts#'>
ALTER TABLE `r_icbil_s` MODIFY COLUMN `DISPEC1` DOUBLE(17,7) NOT NULL DEFAULT '0.00',
 MODIFY COLUMN `DISPEC2` DOUBLE(17,7) NOT NULL DEFAULT '0.00',
 MODIFY COLUMN `DISPEC3` DOUBLE(17,7) NOT NULL DEFAULT '0.00';

</cfquery>