<html>
<head>
<title>Recurring Transaction Group</title>
<link href="/stylesheet/stylesheet.css" rel="stylesheet" type="text/css">
</head>
<body>
<cfoutput>
<h4>
	<a href="recurrtable2.cfm?type=Create">Creating a New Recurring Group</a>||
	<a href="recurrmain.cfm">List all Recurring Group</a>
</h4>
<h1>Recurring Transaction Group</h1>
<cfif isdefined('form.status')>
<h2>
#form.status#
</h2>
</cfif>
<table align="center" class="data" width="800px">
<tr>
<th>
Group ID
</th>
<th>
Desp
</th>
<th>
Type
</th>
<th>
Last Recurring Date
</th>
<th>
Next Recurring Date
</th>
<th>
Last Generated By
</th>
<th>Action</th>
</tr>
<cfquery name="getcurrgroup" datasource="#dts#">
SELECT groupid,desp,recurrtype,lastdate,nextdate,lastgeneratedby FROM recurrgroup
</cfquery>
<cfloop query="getcurrgroup">
<tr>
<td>#getcurrgroup.groupid#</td>
<td>#getcurrgroup.desp#</td>
<td>#getcurrgroup.recurrtype#</td>
<td>#dateformat(getcurrgroup.lastdate,'yyyy-mm-dd')#</td>
<td>#dateformat(getcurrgroup.nextdate,'yyyy-mm-dd')#</td>
<td>#getcurrgroup.lastgeneratedby#</td>
<td><a href="recurrtable2.cfm?type=Edit&id=#getcurrgroup.groupid#"><img height="18px" width="18px" src="/images/edit.ICO" alt="Edit" border="0">Edit</a><a href="recurrtable2.cfm?type=Delete&id=#getcurrgroup.groupid#"><img height="18px" width="18px" src="/images/delete.ICO" alt="Delete" border="0"> Delete</a></td>
</tr>
</cfloop>
</table>
</cfoutput>
</body>
</html>