<cftry>

<cfquery name="geticitem" datasource="#dts#">
SELECT * FROM icitem
</cfquery>

<cfquery name="deleteolditem" datasource="#possvdts#">
delete from icitem9x
</cfquery>

<cfquery name="deleteolditem" datasource="#possvdts#">
delete from icitemp9
</cfquery>


<cfloop query="geticitem">
<cfquery name="insertlist" datasource="#possvdts#" >
INSERT INTO icitemp9
(
ITEMNO,
DISC_R1,
DISC_R10,
DISC_R11,
DISC_R12,
DISC_R13,
DISC_R14,
DISC_R15,
DISC_R16,
DISC_R17,
DISC_R18,
DISC_R19,
DISC_R2,
DISC_R20,
DISC_R3,
DISC_R4,
DISC_R5,
DISC_R6,
DISC_R7,
DISC_R8,
DISC_R9,
PRICE_R1,
PRICE_R10,
PRICE_R11,
PRICE_R12,
PRICE_R13,
PRICE_R14,
PRICE_R15,
PRICE_R16,
PRICE_R17,
PRICE_R18,
PRICE_R19,
PRICE_R2,
PRICE_R20,
PRICE_R3,
PRICE_R4,
PRICE_R5,
PRICE_R6,
PRICE_R7,
PRICE_R8,
PRICE_R9,
QTY_R10A,
QTY_R10B,
QTY_R11A,
QTY_R11B,
QTY_R12A,
QTY_R12B,
QTY_R13A,
QTY_R13B,
QTY_R14A,
QTY_R14B,
QTY_R15A,
QTY_R15B,
QTY_R16A,
QTY_R16B,
QTY_R17A,
QTY_R17B,
QTY_R18A,
QTY_R18B,
QTY_R19A,
QTY_R19B,
QTY_R1A,
QTY_R1B,
QTY_R20A,
QTY_R20B,
QTY_R2A,
QTY_R2B,
QTY_R3A,
QTY_R3B,
QTY_R4A,
QTY_R4B,
QTY_R5A,
QTY_R5B,
QTY_R6A,
QTY_R6B,
QTY_R7A,
QTY_R7B,
QTY_R8A,
QTY_R8B,
QTY_R9A,
QTY_R9B
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.ITEMNO#">,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
)
</cfquery>

<cfquery name="insertlist" datasource="#possvdts#" >
INSERT INTO icitem9x
(
AITEMNO,
BRAND,
CATEGORY,
COMPEC_A,
COMPEC_B,
COMPEC_C,
COSTCODE,
CREATED_ON,
DESP,
DESPA,
EXPIRED,
FACTOR1,
FACTOR2,
FACTORU3_A,
FACTORU3_B,
FACTORU4_A,
FACTORU4_B,
FACTORU5_A,
FACTORU5_B,
FACTORU6_A,
FACTORU6_B,
GRADED,
GROUP,
ITEMNO,
MAXIMUM,
MINIMUM,
MURATIO,
NONSTKITEM,
PACKING,
PHOTO,
POINT,
PRICE,
PRICE2,
PRICE3,
PRICEU2,
PRICEU3,
PRICEU4,
PRICEU5,
PRICEU6,
PRICE_MIN,
PRODCODE,
PROMOTER,
PURC,
PURPRC,
QTYBF,
REMARK1,
REMARK10,
REMARK11,
REMARK12,
REMARK13,
REMARK14,
REMARK15,
REMARK16,
REMARK17,
REMARK18,
REMARK19,
REMARK2,
REMARK20,
REMARK21,
REMARK22,
REMARK23,
REMARK24,
REMARK25,
REMARK26,
REMARK27,
REMARK28,
REMARK29,
REMARK3,
REMARK30,
REMARK4,
REMARK5,
REMARK6,
REMARK7,
REMARK8,
REMARK9,
REORDER,
SALEC,
SALECNC,
SALECSC,
SHELF,
SHORTCODE,
SUPP,
TAXABLE,
TAXPERC1,
TAXPERC2,
UCOST,
UNIT,
UNIT2,
UNIT3,
UNIT4,
UNIT5,
UNIT6,
UPDATED_ON,
WPFORMULA,
WQFORMULA,
WSERIALNO,
DEF_UNIT,
POINTRED,
CATE_DESP,
LOCATION,
LOC_QTYBF,
LOC_PRICE
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.AITEMNO#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.BRAND#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.CATEGORY#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.COMPEC_A)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.COMPEC_B)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.COMPEC_C)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.COSTCODE#">,
<cfif geticitem.created_ON neq "">
{^#dateformat(geticitem.created_ON,'YYYY/MM/DD')#},
<cfelse>
{^#dateformat(now(),'YYYY/MM/DD')#},
</cfif>
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.DESP#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.DESPA#">,
<cfif geticitem.EXPIRED neq "">
{^#dateformat(geticitem.EXPIRED,'YYYY/MM/DD')#},
<cfelse>
{^2001/01/01},
</cfif>
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTOR1)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTOR2)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU3_A)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU3_B)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU4_A)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU4_B)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU5_A)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU5_B)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU6_A)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.FACTORU6_B)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.GRADED#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.WOS_GROUP#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.ITEMNO#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.MAXIMUM)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.MINIMUM)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.MURATIO)#">,
<cfif geticitem.NONSTKITEM eq "T">
.t.,
<cfelse>
.f.,
</cfif>
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PACKING#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PHOTO#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.POINT)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICE)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICE2)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICE3)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICEU2)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICEU3)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICEU4)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICEU5)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICEU6)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.PRICE_MIN)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PRODCODE#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PROMOTOR#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PURC#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.PURPREC#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.QTYBF)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK1#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK10#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK11#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK12#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK13#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK14#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK15#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK16#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK17#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK18#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK19#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK2#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK20#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK21#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK22#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK23#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK24#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK25#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK26#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK27#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK28#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK29#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK3#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK30#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK4#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK5#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK6#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK7#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK8#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.REMARK9#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.REORDER)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SALEC#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SALECNC#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SALECSC#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SHELF#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SHORTCODE#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.SUPP#">,
<cfif geticitem.TAXABLE eq "">
.f.,
<cfelse>
.t.,
</cfif>
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.TAXPERC1)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.TAXPERC2)#">,
<cfqueryparam cfsqltype="cf_sql_float" value="#val(geticitem.UCOST)#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT2#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT3#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT4#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT5#">,
<cfqueryparam cfsqltype="cf_sql_char" value="#geticitem.UNIT6#">,
<cfif geticitem.UPDATED_ON neq "">
{^#dateformat(geticitem.UPDATED_ON,'YYYY/MM/DD')#}
<cfelse>
{^#dateformat(now(),'YYYY/MM/DD')#}
</cfif>
,
<cfif geticitem.WPFORMULA eq "1">
.t.,
<cfelse>
.f.,
</cfif>
<cfif geticitem.WQFORMULA eq "1">
.t.,
<cfelse>
.f.,
</cfif>
<cfif geticitem.WSERIALNO eq "T">
.t.,
<cfelse>
.f.,
</cfif>
0,
0,
'',
'',
0,
0
)
</cfquery>

</cfloop>
<cfcatch></cfcatch></cftry>
