<cfquery name="gettype" datasource="#trim(dts)#">
select * from FTPDETAIL
</cfquery>

<cfquery name="getictran" datasource="#trim(poswsdts)#">
SELECT * FROM ictran9 where type<>'' <cfif gettype.inv eq 1>or type='INV'</cfif> <cfif gettype.do eq 1>or type='DO'</cfif> <cfif gettype.cn eq 1>or type='CN'</cfif> <cfif gettype.dn eq 1>or type='DN'</cfif> <cfif gettype.cs eq 1>or type='CS'</cfif> <cfif gettype.quo eq 1>or type='QUO'</cfif> <cfif gettype.so eq 1>or type='SO'</cfif> <cfif gettype.po eq 1>or type='PO'</cfif> <cfif gettype.rc eq 1>or type='RC'</cfif> <cfif gettype.pr eq 1>or type='PR'</cfif>
</cfquery>
<cfloop query="getictran">
<cfif trim(getictran.custno) eq "9999/999" and getposdetail.custno neq "">
<cfset getictran.custno = getposdetail.custno>
</cfif>
<cfquery name="insertictran" datasource="#trim(dts)#">
INSERT IGNORE INTO ICTRAN
(
REFNO,
TYPE,
TRANCODE,
WOS_DATE,
TRDATETIME,
FPERIOD,
CUSTNO,
NAME,
ITEMCOUNT,
LINECODE,
ITEMNO,
DESP,
DESPA,
SIGN,
QTY,
PRICE,
UNIT,
AMT1,
DISPEC1,
DISPEC2,
DISPEC3,
DISAMT,
AMT,
TAXPEC1,
TAXPEC2,
TAXPEC3,
TAXAMT,
QTY_BIL,
PRICE_BIL,
UNIT_BIL,
AMT1_BIL,
DISAMT_BIL,
AMT_BIL,
TAXAMT_BIL,
BODY,
POINT,
FACTOR1,
FACTOR2,
QTY1,
QTY2,
QTY3,
QTY4,
QTY5,
QTY6,
LOCATION,
CURRRATE,
M_CHARGE1,
M_CHARGE2,
VOID,
AGENNO,
PROMOTER,
MEMBER,
SOURCE,
JOB,
GLTRADAC,
WITHSN,
NOTE1,
NOTE2,
BREM1,
BREM2,
BREM3,
BREM4,
EXPORTED,
GENERATED,
DONO,
TOINV,
BATCHCODE,
TOURGROUP,
UD_QTY
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getposdetail.posbill##REPLACE(getictran.REFNO," ","",'all')#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TYPE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TRANCODE)#">,
"#trim(dateformat(getictran.DATE,'YYYY-MM-DD'))#",
"#trim(TRDATETIME)#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(numberformat(getictran.FPERIOD,'00'))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.CUSTNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NAME)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMCOUNT)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LINECODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESP)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESPA)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SIGN)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.PRICE))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.UNIT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISAMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXAMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.PRICE_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.UNIT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT1_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISAMT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXAMT_BIL))#">,
"#trim(getictran.BODY)#",
"#trim(getictran.POINT)#",
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.FACTOR1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.FACTOR2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY4))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY5))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY6))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LOCATION)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.CURRRATE))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.M_CHARGE1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.M_CHARGE2))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.VOID)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.AGENNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.PROMOTER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.MEMBER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SOURCE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.JOB)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GLTRADAC)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.WITHSN)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM3)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM4)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.EXPORTED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GENERATED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DONO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOINV)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BATCHCODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOURGROUP)#">,
"#trim(getictran.UD_QTY)#"
)
</cfquery>
</cfloop>

<!--- icpso --->
<cftry>
<cfquery name="getictran" datasource="#trim(poswsdts)#">
SELECT * FROM icpso9
</cfquery>
<cfloop query="getictran">
<cfif trim(getictran.custno) eq "9999/999" and getposdetail.custno neq "">
<cfset getictran.custno = getposdetail.custno>
</cfif>
<cfquery name="insertictran" datasource="#trim(dts)#">
INSERT IGNORE INTO ICTRAN
(
REFNO,
TYPE,
TRANCODE,
WOS_DATE,
TRDATETIME,
FPERIOD,
CUSTNO,
NAME,
ITEMCOUNT,
LINECODE,
ITEMNO,
DESP,
DESPA,
SIGN,
QTY,
PRICE,
UNIT,
AMT1,
DISPEC1,
DISPEC2,
DISPEC3,
DISAMT,
AMT,
TAXPEC1,
TAXPEC2,
TAXPEC3,
TAXAMT,
QTY_BIL,
PRICE_BIL,
UNIT_BIL,
AMT1_BIL,
DISAMT_BIL,
AMT_BIL,
TAXAMT_BIL,
BODY,
POINT,
FACTOR1,
FACTOR2,
TOSHIP,
SHIPPED,
QTY1,
QTY2,
QTY3,
QTY4,
QTY5,
QTY6,
LOCATION,
CURRRATE,
M_CHARGE1,
M_CHARGE2,
VOID,
AGENNO,
PROMOTER,
MEMBER,
SOURCE,
JOB,
GLTRADAC,
WITHSN,
NOTE1,
NOTE2,
BREM1,
BREM2,
BREM3,
BREM4,
EXPORTED,
GENERATED,
DONO,
TOINV,
BATCHCODE,
TOURGROUP
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getposdetail.posbill##REPLACE(getictran.REFNO," ","",'all')#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TYPE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TRANCODE)#">,
"#trim(dateformat(getictran.DATE,'YYYY-MM-DD'))#",
"#trim(TRDATETIME)#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(numberformat(getictran.FPERIOD,'00'))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.CUSTNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NAME)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMCOUNT)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LINECODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESP)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESPA)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SIGN)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.PRICE))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.UNIT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISPEC3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISAMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXPEC3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXAMT))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.PRICE_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.UNIT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT1_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.DISAMT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.AMT_BIL))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TAXAMT_BIL))#">,
"#trim(getictran.BODY)#",
"#trim(getictran.POINT)#",
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.FACTOR1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.FACTOR2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.TOSHIP))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.SHIPPED))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY2))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY3))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY4))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY5))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.QTY6))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LOCATION)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.CURRRATE))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.M_CHARGE1))#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#trim(val(getictran.M_CHARGE2))#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.VOID)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.AGENNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.PROMOTER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.MEMBER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SOURCE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.JOB)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GLTRADAC)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.WITHSN)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM3)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM4)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.EXPORTED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GENERATED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DONO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOINV)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BATCHCODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOURGROUP)#">
)
</cfquery>
</cfloop>
<cfcatch type="any">
</cfcatch>
</cftry>