<cfquery name="gettype" datasource="#trim(dts)#">
select * from FTPDETAIL
</cfquery>

<cfquery name="getgrade" datasource="#trim(poswsdts)#">
SELECT * FROM igrade9 where type<>'' <cfif gettype.inv eq 1>or type='INV'</cfif> <cfif gettype.do eq 1>or type='DO'</cfif> <cfif gettype.cn eq 1>or type='CN'</cfif> <cfif gettype.dn eq 1>or type='DN'</cfif> <cfif gettype.cs eq 1>or type='CS'</cfif> <cfif gettype.quo eq 1>or type='QUO'</cfif> <cfif gettype.so eq 1>or type='SO'</cfif> <cfif gettype.po eq 1>or type='PO'</cfif> <cfif gettype.rc eq 1>or type='RC'</cfif> <cfif gettype.pr eq 1>or type='PR'</cfif>
</cfquery>

<cfloop query="getgrade">
<cfquery name="insertgrade" datasource="#trim(dts)#">
INSERT IGNORE INTO igrade
(
TRANCODE,
TYPE,
REFNO,
WOS_DATE,
FPERIOD,
ITEMNO,
SIGN,
LOCATION,
VOID,
EXPORTED,
FACTOR1,
FACTOR2,
GRD11,
GRD12,
GRD13,
GRD14,
GRD15,
GRD16,
GRD17,
GRD18,
GRD19,
GRD20,
GRD21,
GRD22,
GRD23,
GRD24,
GRD25,
GRD26,
GRD27,
GRD28,
GRD29,
GRD30,
GRD31,
GRD32,
GRD33,
GRD34,
GRD35,
GRD36,
GRD37,
GRD38,
GRD39,
GRD40,
GRD41,
GRD42,
GRD43,
GRD44,
GRD45,
GRD46,
GRD47,
GRD48,
GRD49,
GRD50,
GRD51,
GRD52,
GRD53,
GRD54,
GRD55,
GRD56,
GRD57,
GRD58,
GRD59,
GRD60,
GRD61,
GRD62,
GRD63,
GRD64,
GRD65,
GRD66,
GRD67,
GRD68,
GRD69,
GRD70
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.TRANCODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.TYPE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getposdetail.posbill##REPLACE(getgrade.REFNO," ","",'all')#">,
"#trim(dateformat(getgrade.DATE,'YYYY-MM-DD'))#",
"#trim(numberformat(getgrade.FPERIOD,'00'))#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.ITEMNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.SIGN)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.LOCATION)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.VOID)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.EXPORTED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.FACTOR1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.FACTOR2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD11)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD12)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD13)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD14)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD15)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD16)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD17)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD18)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD19)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD20)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD21)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD22)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD23)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD24)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD25)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD26)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD27)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD28)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD29)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD30)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD31)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD32)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD33)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD34)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD35)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD36)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD37)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD38)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD39)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD40)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD41)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD42)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD43)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD44)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD45)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD46)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD47)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD48)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD49)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD50)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD51)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD52)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD53)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD54)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD55)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD56)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD57)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD58)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD59)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD60)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD61)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD62)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD63)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD64)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD65)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD66)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD67)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD68)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD69)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getgrade.GRD70)#">
)
</cfquery>

</cfloop>