<cfquery name="getictran" datasource="importfromdbf">
SELECT * FROM ictran
</cfquery>
<cfloop query="getictran">
<cfquery name="insertictran" datasource="#dts#">
INSERT IGNORE INTO ICTRAN
(
REFNO,
TYPE,
TRANCODE,
WOS_DATE,
TRDATETIME,
FPERIOD,
CUSTNO,
NAME,
ITEMCOUNT,
LINECODE,
ITEMNO,
DESP,
DESPA,
SIGN,
QTY,
PRICE,
UNIT,
AMT1,
DISPEC1,
DISPEC2,
DISPEC3,
DISAMT,
AMT,
TAXPEC1,
TAXPEC2,
TAXPEC3,
TAXAMT,
QTY_BIL,
PRICE_BIL,
UNIT_BIL,
AMT1_BIL,
DISAMT_BIL,
AMT_BIL,
TAXAMT_BIL,
BODY,
POINT,
FACTOR1,
FACTOR2,
QTY1,
QTY2,
QTY3,
QTY4,
QTY5,
QTY6,
LOCATION,
CURRRATE,
M_CHARGE1,
M_CHARGE2,
VOID,
AGENNO,
PROMOTER,
MEMBER,
SOURCE,
JOB,
GLTRADAC,
WITHSN,
NOTE1,
NOTE2,
BREM1,
BREM2,
BREM3,
BREM4,
EXPORTED,
GENERATED,
DONO,
TOINV,
BATCHCODE,
TOURGROUP,
UD_QTY,
comment
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.REFNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TYPE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TRANCODE)#">,
"#dateformat(getictran.DATE,'YYYY-MM-DD')#",
"#TRDATETIME#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#numberformat(getictran.FPERIOD,'00')#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.CUSTNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NAME)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMCOUNT)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LINECODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESP)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESPA)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SIGN)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.PRICE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.UNIT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISAMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXAMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.PRICE_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.UNIT_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT1_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISAMT_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXAMT_BIL)#">,
"#getictran.BODY#",
"#getictran.POINT#",
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.FACTOR1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.FACTOR2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY4)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY5)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY6)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LOCATION)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.CURRRATE)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.M_CHARGE1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.M_CHARGE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.VOID)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.AGENNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.PROMOTER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.MEMBER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SOURCE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.JOB)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GLTRADAC)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.WITHSN)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM3)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM4)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.EXPORTED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GENERATED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DONO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOINV)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BATCHCODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOURGROUP)#">,
"#getictran.UD_QTY#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.comment)#">
)
</cfquery>
</cfloop>

<!--- icpso --->
<cfquery name="getictran" datasource="importfromdbf">
SELECT * FROM icpso
</cfquery>
<cfloop query="getictran">
<cfquery name="insertictran" datasource="#dts#">
INSERT IGNORE INTO ICTRAN
(
REFNO,
TYPE,
TRANCODE,
WOS_DATE,
TRDATETIME,
FPERIOD,
CUSTNO,
NAME,
ITEMCOUNT,
LINECODE,
ITEMNO,
DESP,
DESPA,
SIGN,
QTY,
PRICE,
UNIT,
AMT1,
DISPEC1,
DISPEC2,
DISPEC3,
DISAMT,
AMT,
TAXPEC1,
TAXPEC2,
TAXPEC3,
TAXAMT,
QTY_BIL,
PRICE_BIL,
UNIT_BIL,
AMT1_BIL,
DISAMT_BIL,
AMT_BIL,
TAXAMT_BIL,
BODY,
POINT,
FACTOR1,
FACTOR2,
TOSHIP,
SHIPPED,
QTY1,
QTY2,
QTY3,
QTY4,
QTY5,
QTY6,
LOCATION,
CURRRATE,
M_CHARGE1,
M_CHARGE2,
VOID,
AGENNO,
PROMOTER,
MEMBER,
SOURCE,
JOB,
GLTRADAC,
WITHSN,
NOTE1,
NOTE2,
BREM1,
BREM2,
BREM3,
BREM4,
EXPORTED,
GENERATED,
DONO,
TOINV,
BATCHCODE,
TOURGROUP,
comment
)
VALUES
(
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.REFNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TYPE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TRANCODE)#">,
"#dateformat(getictran.DATE,'YYYY-MM-DD')#",
"#TRDATETIME#",
<cfqueryparam cfsqltype="cf_sql_varchar" value="#numberformat(getictran.FPERIOD,'00')#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.CUSTNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NAME)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMCOUNT)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LINECODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.ITEMNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESP)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DESPA)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SIGN)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.PRICE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UNIT#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISPEC3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISAMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXPEC3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXAMT)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.PRICE_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#getictran.UNIT_BIL#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT1_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.DISAMT_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.AMT_BIL)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TAXAMT_BIL)#">,
"#getictran.BODY#",
"#getictran.POINT#",
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.FACTOR1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.FACTOR2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.TOSHIP)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.SHIPPED)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY2)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY3)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY4)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY5)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.QTY6)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.LOCATION)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.CURRRATE)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.M_CHARGE1)#">,
<cfqueryparam cfsqltype="cf_sql_double" value="#val(getictran.M_CHARGE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.VOID)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.AGENNO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.PROMOTER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.MEMBER)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.SOURCE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.JOB)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GLTRADAC)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.WITHSN)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.NOTE2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM1)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM2)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM3)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BREM4)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.EXPORTED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.GENERATED)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.DONO)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOINV)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.BATCHCODE)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.TOURGROUP)#">,
<cfqueryparam cfsqltype="cf_sql_varchar" value="#trim(getictran.comment)#">
)
</cfquery>
</cfloop>
